# This is a basic workflow to help you get started with Actions

name: Build and Release

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    tags:
      - v[1-9]+.[0-9]+.*

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  publish_nuget:
    if: startsWith(github.ref, 'refs/tags/v')
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.5.0
      with:
      # SDK version to use. Examples: 2.2.104, 3.1, 3.1.x
        dotnet-version: 3.1.x
    - name: Install dependencies
      run: dotnet restore src
    - name: Build
      run: dotnet build src --configuration Release --no-restore
    - name: Pack
      run: dotnet pack src -c Release --no-restore --verbosity normal -o app
    - name: Publish
      run: dotnet nuget push "**/app/*.nupkg" -k ${NUGET_API_KEY} -s https://api.nuget.org/v3/index.json
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
